# Uncomment the next line to define a global platform for your project

target 'satabletennisapp' do
    use_frameworks!
    platform :ios, '9.0'
    pod 'AFNetworking', '3.0'
    RNFirebaseAsStaticFramework = true
    GoogleService-Info.plist
end 